### ISSUE TITLE
Compromised Web Servers and Web Shells

### ISSUE THREAD

**Issue by rhigham-scwx** [rhigham-scwx/shikari#2]
**Title:** Hunt for compromised web servers and web shells 
**Hypothesis:** Threat Actors have gained access to one or more of our externally facing web servers.  
**Trigger:** Common method of attack. We evaluated our coverage and feel this is a gap.
**Reference:** 
- https://attack.mitre.org/techniques/T1505/003/
- https://us-cert.cisa.gov/ncas/alerts/TA15-314A
- https://github.com/Yara-Rules/rules/tree/master/webshells

**Acceptance Criteria**  
This issue can be closed when the abstract has been updated and the report has been written. If the hunt can not be completed, this issue should be marked as blocked. If the hunt is no longer needed, the issue should be labeled as such and then closed.

**Tasks**
- [ ] Check for existing abstract
- [ ] Validate Security Gap Exists
- [ ] Validate Data Visibility/Usability
- [ ] Define/Refine Abstract
- [ ] Gather and Analyze Data
- [ ] Write Report
- [ ] Share Findings
- [ ] Update the Abstract
- [ ] Create New Issue to Repeat the Hunt (if needed)
- [ ] Close this Issue

**Note:** 
- Incidents should be escalated as they are found.
- If an abstract does not exist that can be updated and reused, create a new abstract.
- If you plan to test to make sure the security gap exists through adversary emulation, notify your manager and security operations.
- If you find inappropriate content or other compliance issues, check with management to determine next steps.
- If this hunt did not produce logic that can be used to address the known gap, open a new issue to repeat the hunt in the future.
