### ISSUE TITLE
Compromised Email Accounts

### ISSUE THREAD

**Issue by rhigham-scwx** [rhigham-scwx/shikari#3]
**Title:** Hunt for Compromised Email Accounts
**Hypothesis:** Business email compromise has become a very common method of attack.
**Trigger:** Threat Actor Intel 
**Reference:**
- https://attack.mitre.org/techniques/T1114/003/
- https://attack.mitre.org/techniques/T1078/004/
- https://docs.microsoft.com/en-us/archive/blogs/timmcmic/exchange-and-office-365-mail-forwarding-2

**Acceptance Criteria**  
This issue can be closed when the abstract has been updated and the report has been written. If the hunt can not be completed, this issue should be marked as blocked. If the hunt is no longer needed, the issue should be labeled as such and then closed.

**Tasks**
- [ ] Validate Security Gap Exists
- [ ] Validate Data Visibility/Usability
- [ ] Define/Refine Abstract
- [ ] Gather and Analyze Data
- [ ] Write Report
- [ ] Share Findings
- [ ] Update the Abstract
- [ ] Create New Issue to Repeat the Hunt (if needed)
- [ ] Close this Issue

**Note:** 
- Incidents should be escalated as they are found.
- If an abstract does not exist that can be updated and reused, create a new abstract.
- If you plan to test to make sure the security gap exists through adversary emulation, notify your manager and security operations.
- If you find inappropriate content or other compliance issues, check with management to determine next steps.
- If this hunt did not produce logic that can be used to address the known gap, open a new issue to repeat the hunt in the future.
