### ISSUE TITLE
Detect ADFS Misuse

### ISSUE THREAD

**Issue by rhigham-scwx** [rhigham-scwx/shikari#7]
**Title:** Detect ADFS Misuse
**Hypothesis:** Threat actors are exploiting adfs
**Trigger:** Threat Intel surrounding the SolarWinds breach 
**Reference:**
* https://attack.mitre.org/techniques/T1005/
* https://techcommunity.microsoft.com/t5/azure-sentinel/solarwinds-post-compromise-hunting-with-azure-sentinel/ba-p/1995095
   * detect adfsspoof or adfsdump (yara, image_path, commandline, etc)
   * find supsicious adfs master key export event 4662
   * image_path = Microsoft.IdentityServer.ServiceHost.exe
   * https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/SolarWindsPostCompromiseHunting.json 
   * Importantly, if you have recently rotated ADFS key material this workbook can be useful in identifying attacker logon activity if they logon with old key material. Look for the change activity and anything after the change using the old material.
* https://www.cybersecurity-help.cz/vdb/SB2019071015
   * A remote attacker can convince the ADFS administrator to update a list of banned IP addresses and bypass security restrictions
   * A remote attacker can perform a brute-force attack and cause account lockouts in Active Directory.
*  https://www.fireeye.com/blog/threat-research/2021/04/abusing-replication-stealing-adfs-secrets-over-the-network.html
   * alert on HTTP POST requests to the address that hosts the Policy Store Transfer service. If there is an AD FS farm, then the IP addresses of the AD FS servers will need to be whitelisted against the rule.

**Acceptance Criteria**  
This issue can be closed when the abstract has been updated and the report has been written. If the hunt can not be completed, this issue should be marked as blocked. If the hunt is no longer needed, the issue should be labeled as such and then closed.

**Tasks**
- [ ] Validate Security Gap Exists
- [ ] Validate Data Visibility/Usability
- [ ] Define/Refine Abstract
- [ ] Gather and Analyze Data
- [ ] Write Report
- [ ] Share Findings
- [ ] Update the Abstract
- [ ] Create New Issue to Repeat the Hunt (if needed)
- [ ] Close this Issue

**Note:** 
- Incidents should be escalated as they are found.
- If an abstract does not exist that can be updated and reused, create a new abstract.
- If you plan to test to make sure the security gap exists through adversary emulation, notify your manager and security operations.
- If you find inappropriate content or other compliance issues, check with management to determine next steps.
- If this hunt did not produce logic that can be used to address the known gap, open a new issue to repeat the hunt in the future.
